import {
  avatar1,
  avatar10,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  pledge1,
  pledge2,
  pledge3,
  pledge4,
  pledge5,
  pledge6,
} from "../assets/images";

export const pledge = [
  {
    id: "22",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge1,
    creator: "1000",
    creatorImg: avatar1,
    currentBid: "4999",
    percent: 2.4,
    days: 2,
    people: 43100,
    min: 1000,
    max: 4999,
  },

  {
    id: "23",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge2,
    creator: "5000",
    creatorImg: avatar2,
    currentBid: "9999",
    percent: 3,
    days: 4,
    people: 41700,
    min: 5000,
    max: 9999,
  },

  {
    id: "24",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge3,
    creator: "10000",
    creatorImg: avatar3,
    currentBid: "49999",
    percent: 3.5,
    days: 7,
    people: 44800,
    min: 10000,
    max: 49999,
  },

  {
    id: "25",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge4,
    creator: "50000",
    creatorImg: avatar4,
    currentBid: "99999",
    percent: 4,
    days: 14,
    people: 47100,
    min: 50000,
    max: 99999,
  },

  {
    id: "26",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge5,
    creator: "100000",
    creatorImg: avatar5,
    currentBid: "199999",
    percent: 4.5,
    days: 21,
    people: 46300,
    min: 100000,
    max: 199999,
  },

  {
    id: "27",
    title: "BoredApe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam adipisci cupiditate officia, nostrum et deleniti vero corrupti facilis minima laborum nesciunt nulla error natus saepe illum quasi ratione suscipit tempore dolores. Recusandae, similique modi voluptates dolore repellat eum earum sint.",
    imgUrl: pledge6,
    creator: "200000",
    creatorImg: avatar10,
    currentBid: "500000",
    percent: 5,
    days: 30,
    people: 43900,
    min: 200000,
    max: 500000,
  },
];
